chain:
  bech32_prefix: YOUR_CHAIN_ACC_PREFIX
  modules:
    - addresses
    - assetft
    - assetnft
    - auth
    - bank
    - consensus
    - customparams
    - daily refetch
    - dex
    - distribution
    - feegrant
    - feemodel
    - gov
    - mint
    - pricefeed
    - slashing
    - staking
    - telemetry
    - upgrade

node:
  type: remote
  config:
    rpc:
      client_name: juno
      address: http://YOUR_NODE_IP:26657
      max_connections: 20
    grpc:
      address: YOUR_NODE_IP:9090
      insecure: true
    api:
      address: http://YOUR_NODE_IP:1317
parsing:
  workers: 20
  start_height: 1
  average_block_time: 5s
  listen_new_blocks: true
  parse_old_blocks: true
  parse_genesis: true
  genesis_file_path: ".callisto/genesis.json"
database:
  url: postgresql://postgres:password@localhost:5432/?sslmode=disable&search_path=public
  max_open_connections: 10
  max_idle_connections: 10
  partition_size: 100000
  partition_batch: 1000
  ssl_mode_enable: "false"
  ssl_root_cert: ""
  ssl_cert: ""
  ssl_key: ""
logging:
  level: debug
  format: text
actions:
  port: 3000
pricefeed:
  tokens:
    - name: coreum
      units:
        - denom: coreum
          exponent: 6
          price_id: coreum