chain:
    bech32_prefix: YOUR_CHAIN_ACC_PREFIX
    modules:
        - modules
        - messages
        - auth
        - bank
        - consensus
        - gov
        - mint
        - slashing
        - staking
        - distribution
        - actions
        - feemodel
        - customparams
        - assetft
        - assetnft
        - pricefeed
        - wasm
node:
    type: remote
    config:
        rpc:
            client_name: juno
            address: http://YOUR_NODE_IP:26657
            max_connections: 20
        grpc:
            address: http://YOUR_NODE_IP:9090
            insecure: true
parsing:
    workers: 20
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
    fast_sync: false
    genesis_file_path: ".bdjuno/genesis.json"
    average_block_time: 1s

database:
    name: root # This is the defaults, but might be updated
    host: postgres
    port: 5432
    user: root
    password: password
    schema: public
    max_open_connections: 20
    max_idle_connections: 20
    partition_size: 100000
    partition_batch: 1000

logging:
    level: info
    format: text

telemetry:
    port: 5000

pruning:
    keep_recent: 100
    keep_every: 500
    interval: 10

actions:
    port: 3000

pricefeed:
    tokens:
        - name: coreum
          units:
              - denom: coreum
                exponent: 6
                price_id: coreum