name: Build and Push to DockerHub

on:
  push:
    branches:
      - chains/coreum

env:
  BDJUNO_IMAGE_NAME: bdjuno
  HASURA_IMAGE_NAME: hasura
  ORG: coreumfoundation

jobs:
  setup-build-publish-webhook:
    name: Setup, Build, Publish, Webhook
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set variables
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
          echo "SHA8=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push bdjuno
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          tags: |
            ${{ env.ORG }}/${{ env.BDJUNO_IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.ORG }}/${{ env.BDJUNO_IMAGE_NAME }}:${{ env.SHA8 }}
            ${{ env.ORG }}/${{ env.BDJUNO_IMAGE_NAME }}:latest

      - name: Build and push hasura
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.hasura
          push: true
          tags: |
            ${{ env.ORG }}/${{ env.HASURA_IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.ORG }}/${{ env.HASURA_IMAGE_NAME }}:${{ env.SHA8 }}
            ${{ env.ORG }}/${{ env.HASURA_IMAGE_NAME }}:latest