name: ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 1 * * 1' # At 01:00 on Monday
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        ci_step: [
          "test",
        ]
        include:
          - ci_step: "test"
            command: "bdjuno-builder test"
            linter-cache: false
            codecov: true
            codecov-name: coreum

    runs-on: ubuntu-22.04
    steps:
      - name: Go version used to build builder
        run: go version
      - name: Checkout bdjuno
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          path: bdjuno
      - name: Set up build system
        run: |
          echo "$(pwd)/bdjuno/bin" >> $GITHUB_PATH
      - name: Retrieve go version
        id: goversion
        run: echo "GO_VERSION=$(bdjuno/bin/go version)" >> $GITHUB_OUTPUT
      - name: Print go version
        run: echo ${{ steps.goversion.outputs.GO_VERSION }}
      - name: Setup go cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-v2-${{ hashFiles('**/go.sum') }}-${{ steps.goversion.outputs.GO_VERSION }}
      - name: Prepare dependencies
        run: |
          bdjuno-builder build/me
          bdjuno-builder download
      - name: Run ${{ matrix.ci_step }}
        run: ${{ matrix.command }}
