name: ci
on:
  push:
    branches: [ chains/coreum ]
  pull_request:
    branches: [ chains/coreum ]
  schedule:
    - cron: '0 1 * * 1' # At 01:00 on Monday
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        ci_step: [
          "test",
        ]
        include:
          - ci_step: "test"
            command: make test
            codecov: true
            codecov-name: coreum

    runs-on: self-hosted
    steps:
      - name: Go version used to build builder
        run: go version
      - name: Checkout bdjuno
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Run ${{ matrix.ci_step }}
        run: ${{ matrix.command }}
