name: Build and Push to DockerHub

on:
  push:
    branches:
      - chains/coreum-v0.50.x
  pull_request:
    branches:
      - chains/coreum-v0.50.x # FIXME remove

jobs:
  build-publish-docker:
    name: Build and Push to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish images
        run: make release-images