name: Lint
# Lint runs golangci-lint over the entire Desmos repository.
# This workflow is run on every pull request and push to master.
# The `golangci` will pass without running if no *.{go, mod, sum} files have been changed.
on:
  pull_request:
    branches:
      - main
      - chains/coreum
  push:
      - chains/coreum

jobs:
  GolangCI:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Go 🧰
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Compute diff 📜
        uses: technote-space/get-diff-action@v6.1.2
        with:
          SUFFIX_FILTER: |
            .go
            .mod
            .sum
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.0
          args: --timeout 10m
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: "env.GIT_DIFF != ''"
